---

- name: "service | Install coredns systemd service file"
  become: yes
  ansible.builtin.template:
    src: templates/coredns.service.j2
    dest: /etc/systemd/system/coredns.service
    owner: root
    group: root
    mode: 0444
  notify: "handler | Restart coredns"

- name: "service | Ensure CoreDNS is enabled on boot"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ coredns_service_name }}"
    enabled: true